-- Migration: Initial Schema for Gravity Hybrid Memory
-- Tier 1 & Tier 2 Implementation

CREATE SCHEMA IF NOT EXISTS gravity;

-- T1: Core Memory (Permanent Facts)
CREATE TABLE IF NOT EXISTS gravity.core_memory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    category TEXT DEFAULT 'general',
    metadata JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, key)
);

-- T2: Conversation Buffer (Messages)
CREATE TABLE IF NOT EXISTS gravity.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- T2: Summaries (Context compression)
CREATE TABLE IF NOT EXISTS gravity.summaries (
    chat_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    summary TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_core_memory_user ON gravity.core_memory(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_chat_id ON gravity.messages(chat_id);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON gravity.messages(user_id);
